Env: Dev
Common:
  Dev:
    AttachUrl: http://192.168.1.40:8090
    AttachPath: /home/wwwroot/sensorexpert/application/attachment
  Test:
    AttachUrl: http://192.168.1.45:8090
    AttachPath: /home/attachment
  Prod:
    AttachUrl: "http://static.spiderhub.net"
    AttachPath: "/home/attachment"
Log:
  Dev:
    Level: debug        #Emergency   Alert  Critical  Error  Warning  Info  Debug
    Path: runtime/logs
    Name: default
  Test:
    Level: debug        #Emergency   Alert  Critical  Error  Warning  Info  Debug
    Path: runtime/logs
    Name: default
  Prod:
    Level: error
    Path: runtime/logs
    Name: default
Queue:
  Dev:
    Uri: "amqp://guest:guest@192.168.1.40:5672/"
  Test:
    Uri: "amqp://guest:guest@127.0.0.1:5672/"
  Prod:
    Uri: "amqp://guest:guest@127.0.0.1:5672/"
Redis:
  Dev:
    Proto: tcp    #tcp|udp
    Addr: 192.168.1.40:6379
    Password: ""
    Db: 0
    MaxActive: 0     # 最大活动连接数，值为0时表示不限制
    MaxIdle: 10 #最大空闲连接数
    IdleTimeout: 600 #空闲连接的超时时间，超过该时间则关闭连接。单位为秒。默认值是5分钟。值为0时表示不关闭空闲连接。此值应该总是大于redis服务的超时时间。
    Prefix: ""  #键名前缀
  Test:
    Proto: tcp    #tcp|udp
    Addr: 127.0.0.1:6379
    Password: ""
    Db: 0
    MaxActive: 0     # 最大活动连接数，值为0时表示不限制
    MaxIdle: 10 #最大空闲连接数
    IdleTimeout: 600 #空闲连接的超时时间，超过该时间则关闭连接。单位为秒。默认值是5分钟。值为0时表示不关闭空闲连接。此值应该总是大于redis服务的超时时间。
    Prefix: ""  #键名前缀
  Prod:
    Proto: tcp    #tcp|udp
    Addr: 127.0.0.1:6379
    Password: ""
    Db: 0
    MaxActive: 0     # 最大活动连接数，值为0时表示不限制
    MaxIdle: 10 #最大空闲连接数
    IdleTimeout: 600 #空闲连接的超时时间，超过该时间则关闭连接。单位为秒。默认值是5分钟。值为0时表示不关闭空闲连接。此值应该总是大于redis服务的超时时间。
    Prefix: ""  #键名前缀
Mongo:
  Dev:
    Host: 192.168.1.40
    Port: 27017
    User: ""
    Password: ""
    Dbs:
      - spider_main
      - spider_data
  Test:
    Host: 192.168.1.40
    Port: 27017
    User: ""
    Password: ""
    Dbs:
      - spider_main
      - spider_data
  Prod:
    Host: 127.0.0.1
    Port: 27017
    User: ""
    Password: ""
    Dbs:
      - spider_main
      - spider_data
Mysql:
  Dev:
    Host: 192.168.1.40:3306
    User: root
    Password: 123456
    Dbs:
      - spiderhub
  Test:
    Host: 127.0.0.1:3306
    User:
    Password: ""
    Dbs:
      - spiderhub
  Prod:
    Host: 127.0.0.1:3306
    User: ""
    Password: ""
    Dbs:
      - spiderhub
Backend:
  Dev:
    Addr: :8080
    Level: debug
    Reload: true
  Test:
    Addr: :8080
    Level: info
    Reload: true
  Prod:
    Addr: :8080
    Level: error
    Reload: false